name: twirp_dart_core
description: Core library for using Twirp + Dart
version: 1.0.0+3
homepage: https://github.com/apptreesoftware/twirp_dart_core
author: Matthew Smith<matthew.smith@apptreesoftware.com>

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  http: ^0.13.3
  requester:
    git:
      url: git://github.com/unicomp21/requester
dev_dependencies:
  test: ^1.16.5
